### PR TITLE
Return Content-Length header

### PR DESCRIPTION
**Pull request by naksu**
I had trouble using rack-coffee through Nginx. Nginx gives a warning about missing Content-Length header (when compression is not used). This change adds the missing header.

### CODE REVIEW

**Comment by mattly** [comment]
Thanks! I'll take a look at doing a merge / release this afternoon.

**Comment by mattly** [comment]
However, I'm pretty sure something in the Rack stack is supposed to handle the Content-Length header for you. It's been a while since I've dealt with this.

**Comment by mattly** [comment]
There is a middleware for this, it's even included in Rack (not stuffed into rack/contrib): https://github.com/rack/rack/blob/master/lib/rack/content_length.rb

If you  'use Rack::ContentLength' in your config.ru before any of your content-generating middleware it will handle all of your requests.

That said, it'd be a nice feature to have, so I'll have to take a look later at why Travis says the PR isn't building and GH says it can't merge cleanly.

**Comment by naksu** [comment]
Thanks Matthew, 

Unfortunately, Rack::ContentLength is not compatible with an event-driven web server (Thin). It does not work correctly if higher-level middleware performs an asynchronous operation (such as EventMachine::Synchrony.sleep(0)). I could write a version that does work asynchronously, but adding the header in rack-coffee seemed to me like a more correct thing to do.

I added a bug fix on my branch, 498701eb62b24fc8daff92440f49dc56593ab1d9. Should I create a pull request for that, too?

Travis error seems to say that it cannot find Rubinius binaries.

**Comment by mattly** [comment]
Ah, understood. And, you're right, adding the header is the right thing to do – we know the length, we may as well send it along. I should have some time this afternoon to deal with this.

I conceived of Rack::Coffee as a development tool back when CoffeeScript was written in Ruby and before its CLI had a `--watch` option, and assumed anyone wanting to serve CS in production would pre-compile it. Just goes to show...

**Comment by mattly** [comment]
closed by #ee95b4e

I fixed travis manually, they changed how rubinius tests are handled.

**Pull request closed without merging**
